# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2b20c32027adc779047b34d4d0108062"
name = "Distributor Map"
application_url = "https://distributor-map-app.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[[webhooks.subscriptions]]
topics = ["app/uninstalled", "products/delete"]
uri = "/api/webhooks"

[access.admin]
direct_api_mode = "online"
embedded_app_direct_api_access = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]

[sidekick]
extensions_summary = "Manage retail locations, products, and storefront store locator settings."

[app_proxy]
url = "https://distributor-map-app.onrender.com/api/storefront"
subpath = "distributor-map"
prefix = "apps"


